### ISSUE TITLE
undefined method `except' for :too_large:Symbol

### ISSUE THREAD

**Issue by asiniy** [elabs/refile#137]
I get this exception when I try to upload file bigger than constrained size & specify `type: :image` constraint and try to upload `.pdf` document. I don't catch an exception when I upload image.

`undefined method 'except' for :too_large:Symbol`
 in `activemodel 4.2.0 in lib/active_model/errors.rb line 449`

``` ruby
  attachment :avatar#, type: :image # if comment type: :image, I don't get exception and get standard activemodel error.
```

This is how I add file size constraints to the backend

``` ruby
#config/initializers/refile.rb
Refile.cache = Refile::Backend::FileSystem.new('public/uploads/cache', max_size: 1.megabytes)
Refile.store = Refile::Backend::FileSystem.new('public/uploads/store', max_size: 1.megabytes)
```

**Comment by jnicklas** [comment]
Stack trace please ;)

**Comment by asiniy** [comment]
```
Started PUT "/users" for 127.0.0.1 at 2015-01-30 18:40:28 +0300
Processing by RegistrationsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"w4w53ukgF+hw9O9VOQhyNcugctp6IQIofc2UO3mw06evT88DZe3PaxqJlUtqbPK9W1xvFJq5qhV5mbIhyxOhmw==", "user"=>{"email"=>"marcus_keebler@yahoo.com", "first_name"=>"Russ", "last_name"=>"Pollich", "phone"=>"+7 (921) 111-11-11", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x00000007f76af0 @tempfile=#<Tempfile:/tmp/RackMultipart20150130-7271-1hyw2df.pdf>, @original_filename="Руководство по эксплуатации FoodBox.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"\xD0\xA0\xD1\x83\xD0\xBA\xD0\xBE\xD0\xB2\xD0\xBE\xD0\xB4\xD1\x81\xD1\x82\xD0\xB2\xD0\xBE \xD0\xBF\xD0\xBE \xD1\x8D\xD0\xBA\xD1\x81\xD0\xBF\xD0\xBB\xD1\x83\xD0\xB0\xD1\x82\xD0\xB0\xD1\x86\xD0\xB8\xD0\xB8 FoodBox.pdf\"\r\nContent-Type: application/pdf\r\n">, "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "current_password"=>"[FILTERED]"}, "commit"=>"Сохранить настройки"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 109ms

NoMethodError - undefined method `except' for :too_large:Symbol:
  activemodel (4.2.0) lib/active_model/errors.rb:449:in `normalize_message'
  activemodel (4.2.0) lib/active_model/errors.rb:300:in `add'
  refile (0.5.3) lib/refile/attachment/active_record.rb:18:in `block in attachment'
  activesupport (4.2.0) lib/active_support/callbacks.rb:441:in `block in make_lambda'
  activesupport (4.2.0) lib/active_support/callbacks.rb:189:in `block in simple'
  activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `block in simple'
  activesupport (4.2.0) lib/active_support/callbacks.rb:182:in `block in conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:182:in `block in conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:182:in `block in conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:182:in `block in conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:182:in `block in conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_validate_callbacks'
  activemodel (4.2.0) lib/active_model/validations.rb:395:in `run_validations!'
  activemodel (4.2.0) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_validation_callbacks'
  activemodel (4.2.0) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
  activemodel (4.2.0) lib/active_model/validations.rb:334:in `valid?'
  activerecord (4.2.0) lib/active_record/validations.rb:58:in `valid?'
  activerecord (4.2.0) lib/active_record/validations.rb:83:in `perform_validations'
  activerecord (4.2.0) lib/active_record/validations.rb:37:in `save'
  activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.2.0) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  activerecord (4.2.0) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.0) lib/active_record/transactions.rb:286:in `block in save'
  activerecord (4.2.0) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  activerecord (4.2.0) lib/active_record/transactions.rb:285:in `save'
  activerecord (4.2.0) lib/active_record/persistence.rb:250:in `block in update'
  activerecord (4.2.0) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.0) lib/active_record/persistence.rb:248:in `update'
  devise (3.4.1) lib/devise/models/database_authenticatable.rb:74:in `update_with_password'
  devise (3.4.1) app/controllers/devise/registrations_controller.rb:99:in `update_resource'
  devise (3.4.1) app/controllers/devise/registrations_controller.rb:53:in `update'
  app/controllers/registrations_controller.rb:6:in `update'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:57:in `call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.4) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'

```

**Comment by jnicklas** [comment]
Back from vacation, sorry it took me a while to look at this. Was a pretty easy fix, I wasn't using the `add` method correctly.

**Comment by asiniy** [comment]
@jnicklas, thanks!
